import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; 
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        {/* Aqui pode colocar layouts que são comuns entre as páginas. exemplo header com menu. */}
        {children}
      </body>
      {/* Aqui pode colocar layouts que são comuns entre as páginas. exemplo rodapé */}
    </html>
  );
}
